# Generated by Django 4.1.3 on 2022-11-14 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='cumpleaños',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
